---

- name: Deploy web app
  hosts: all

  vars_files:
    - vars/credentials.yml

  vars:
    ansible_become_pass: "{{ ansible_ssh_password }}"
    app_version: 1.0.0-SNAPSHOT

  tasks:
    - name: Delete jar
      file:
        state: absent
        path: ~/nikitaaero/jenkins-practice/app.jar

    - name: Delete script
      file:
        state: absent
        path: ~/nikitaaero/jenkins-practice/run.sh

    - name: Creates dir
      file:
        path: ~/nikitaaero/jenkins-practice
        state: directory

    - name: Copy project jar
      copy:
        src: "./app-jenkins-practice-{{ app_version }}.jar"
        dest: ~/nikitaaero/jenkins-practice/app.jar

    - name: Copy run script
      copy:
        src: run.sh
        dest: ~/nikitaaero/jenkins-practice/

    - name: Executable mod for run script
      file:
        dest: ~/nikitaaero/jenkins-practice/run.sh
        mode: +x

    - name: Run app
      shell: nohup ~/nikitaaero/jenkins-practice/run.sh

